### ISSUE TITLE
Peer relationship and Quote

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#113]
For both sites (mm.mmk.interledger) (us.usd.interledger) I have shared public peer keys for the trust line relationship and using MQTT Broker: mqtt://broker.hivemq.com:1883. However, I am not getting a quote for either of peers with any sites. (USD, MMK). 

But Red and Blue are working fine with USD / EUR. How can I setup to get a quote for exotic currencies pairs?

By the way, can I set up the quote for exchange including to charge 0.1% of current rates?

**Comment by justmoon** [comment]
> How can I setup to get a quote for exotic currencies pairs?

The connector uses backends for getting liquidity information. Currently, the default backend is an API called `fixer.io`, which doesn't provide rates for MMK.

In order to support MMK, you need a source for exchange rates and then copy the [fixer.io backend](https://github.com/interledgerjs/ilp-connector/blob/master/src/backends/fixerio/index.js) and write your own version using your other data source. (We plan on making this easier in the future!)

> By the way, can I set up the quote for exchange including to charge 0.1% of current rates?

Yes, you can use the `CONNECTOR_FX_SPREAD` configuration variable. See [connector README](https://github.com/interledgerjs/ilp-connector#ilp-connector---).

**Comment by Winthan** [comment]
@justmoon  Thanks for the info.

btw, can we use Yahoo's Exchange API than fixer.io. The Yahoo Exchange can cover most of the currencies as well as BTC/Gold/Slivers so on. 

`https://query.yahooapis.com/v1/public/yql?q=select * from yahoo.finance.xchange where pair in ("USDAUD", "USDAED", "USDARS", "USDAOA", "USDBGN", "USDBRL", "USDBTC", "USDBRL", "USDCAD", "USDCHF", "USDCNY", "USDCZK", "USDDKK", "USDEUR", "USDGBP", "USDHKD", "USDHRK", "USDHUF", "USDIDR", "USDILS",   "USDISK", "USDLTL", "USDLVL", "USDRON", "USDJPY",  "USDKRW", "USDMMK", "USDMXN",  "USDMYR",  "USDMZN", "USDNOK", "USDNZD", "USDPHP", "USDPLN", "USDRON", "USDRUB", "USDSEK", "USDSGD", "USDTHB", "USDTRY", "USDTWD", "USDXAG", "USDXAU",  "USDZAR")&env=store://datatables.org/alltableswithkeys&format=json `

**Comment by justmoon** [comment]
Great suggestion @Winthan - created an issue: https://github.com/interledgerjs/ilp-connector/issues/279
