### ISSUE TITLE
Admin issue

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#114]
Due to known issue of admin, I set to balance with some number for admin to have enough balance in the database. But I feel like this is not the way I issue admin to credit. this should not be able to set balance manually in the database.

 Later, I am trying to set to null at balance for balance. I got this error. 
```
ilpkit=> update "L_ACCOUNTS" set "BALANCE" = null WHERE "ACCOUNT_ID" = 2 ;
ERROR:  null value in column "BALANCE" violates not-null constraint
DETAIL:  Failing row contains (2, admin, null, AAAAQAAAAQDcQnz4hAUlAeNvXuuDmcCptzosKY6ZLWgEh6ICe4AF4P/I6rcO6wKQ..., null, 1, 0, null, 0.0000000000000000, 2016-12-11 02:10:58.22128+00, 2016-12-07 12:35:34.812623+00, ilpkit).
```

**Comment by sharafian** [comment]
As of https://github.com/interledgerjs/ilp-kit/commit/3ab3a9a504abcbfd817049f6f429d8a10f848fe3 , the admin account has a default `minimum_allowed_balance` of `-infinity`. Instead of issuing credit to the admin, you should issue credit out of the admin account, making the admin account's balance go negative.

If you really need to set an account's balance for some reason, you can make a `PUT` to that account's endpoint (authenticated with admin credentials), and include a JSON object with the field `"balance"` in it. However, that functionality is [going to be taken out](https://github.com/interledgerjs/five-bells-ledger/issues/370), because setting balances manually makes the ledger inconsistent (the sum of all balances should add to zero).
