### ISSUE TITLE
In peers list, display max/min balance (and other improvements)

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#202]
In this screenshot of my Peers page, it's not clear to me:

* what the green 'online' dot means (only two of my four peers are actually online, but all are green)
* what the 'Destination' number means
* ~~what the currency for each balance is~~ -> see this now, it's on the left
* what the current min/max Balance for each peer is

![screen shot 2017-02-09 at 11 10 20](https://cloud.githubusercontent.com/assets/408412/22778790/72a148d2-eeb8-11e6-9176-5967769c2920.png)

Assuming that a negative balance means I owe that peer money, and vice versa for positive balance, there is a minimum and a maximum balance. So:
By Min Balance I mean the amount for which that peer trusts me.
By Max Balance I mean the amount for which I trust that peer.

Stretch goal: add a "Balance peers" button. ;)

**Comment by michielbdejong** [comment]
Ah wait, I just realized that 'Limit' is the 'Max Balance'. So all that's missing then is 'Min Balance'.

It would also be good if hosts that peer with me are displayed, so that I can discover that and peer back with them.

**Comment by vhpoet** [comment]
> what the currency for each balance is -> see this now, it's on the left

Fixed with the latest redesign

**Comment by michielbdejong** [comment]
Wow! :)

> > Stretch goal: add a "Balance peers" button. ;)
>
> Is that different from the "settle" button?

It was more of a "joke to self", not a serious suggestion. Please ignore it, sorry :)

**Comment by vhpoet** [comment]
@michielbdejong Here's [another commit](https://github.com/interledgerjs/ilp-kit/commit/3b85f0869e4ced76373e113b723f71ec81069530) that makes the Peers page look better.

- online indicator is fixed
- destination number is removed (shouldn't be used manually)
- currency is shown next to the numbers
- min/max balance is more clear

There's still a lot to do on the Peers page, but closing this now since I assume your concerns are addressed. Feel free to reopen if I missed anything.

**Comment by michielbdejong** [comment]
Awesome!
