### ISSUE TITLE
Clean up branch names

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#353]
Right now it may be confusing to a new user coming in from the open source community as there are branches named
master
latest
release

lets consolidate and agree on 1 branch that should be the tip.

**Comment by dappelt** [comment]
@michielbdejong

**Comment by michielbdejong** [comment]
Fixed in https://github.com/interledgerjs/ilp-kit/pull/350, for the Heroku and Docker builds, as well as for the manual DigitalOcean and GCE instructions. Once that is merged, I'll delete the 'latest' branch.

The branch we should run in production is now called 'release' (since 'latest' was a bad name).

The branch we should develop is still called master, and we cut a release from master every two weeks.
