### ISSUE TITLE
RegExp DoS issue?

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#403]
The install log shows:
```
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

This is not [reported by snyk](https://snyk.io/test/github/interledgerjs/ilp-kit) apparently
And also, it seems we're [no longer using snyk](https://github.com/interledgerjs/ilp-kit/commits/86dcb)?

cc @dappelt

**Comment by dappelt** [comment]
> This is not reported by snyk apparently

`minimatch@0.3.0` is introduced through `mocha`. Synk has this vulnerability in its [DB](https://snyk.io/vuln/npm:minimatch:20160620), but I assume Snyk does not report this because mocha is a dev dependency. 

I don't think this vulnerability is exploitable. If it does not cause any problems, we can upgrade mocha to avoid the warning you reported.

> And also, it seems we're no longer using snyk?

We are still using Snyk, I just removed the badge.

**Comment by michielbdejong** [comment]
ok!
